import { useState, useEffect } from 'react'
import toast from 'react-hot-toast'
import SearchableDropdown from '../SearchableDropdown'
import FormattedNumberInput from '../FormattedNumberInput'
import { formatNumber } from '../../helper/formatHelper'

const generatePurchaseName = () =>
  `Purchase ${new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`

const PurchaseForm = ({
  initialValues,
  items = [],
  onSubmit,
  onCancel,
  isEdit,
}) => {
  const [name, setName] = useState('')
  const [nameWasAutogenerated, setNameWasAutogenerated] = useState(false)
  const [description, setDescription] = useState('')
  const [item, setItem] = useState('')
  const [quantity, setQuantity] = useState(1)
  const [quantityPerUnit, setQuantityPerUnit] = useState(1)
  const [total, setTotal] = useState(0)

  const itemOptions = items.map((i) => {
    const suffix = i.unitSet?.symbol ?? i.unitSet?.description ?? ''
    const label = suffix ? `${i.name} (${suffix})` : i.name
    return { _id: i._id, label }
  })

  const totalItemAmount = Number(quantity) * Number(quantityPerUnit)
  const effectivePerUnit = Number(quantity) > 0 ? Number(total) / Number(quantity) : 0
  const selectedItem = items.find((i) => i._id === item)
  const preferredSymbol = selectedItem?.unitSet?.symbol ?? selectedItem?.unitSet?.description ?? ''

  useEffect(() => {
    if (initialValues) {
      setName(initialValues.name ?? '')
      setNameWasAutogenerated(false)
      setDescription(initialValues.description ?? '')
      setItem(initialValues.item?._id ?? initialValues.item ?? '')
      setQuantity(Math.max(1, Number(initialValues.quantity) || 1))
      setQuantityPerUnit(initialValues.quantityPerUnit ?? 1)
      setTotal(initialValues.total ?? 0)
    } else {
      setName(generatePurchaseName())
      setNameWasAutogenerated(true)
      setDescription('')
      setItem('')
      setQuantity(1)
      setQuantityPerUnit(1)
      setTotal(0)
    }
  }, [initialValues, items])

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!item || !item.trim()) {
      toast.error('Please select an item')
      return
    }
    const qty = Number(quantity) || 0
    const totalAmount = Number(total) || 0
    if (qty <= 0) {
      toast.error('Quantity must be greater than 0')
      return
    }
    if (totalAmount <= 0) {
      toast.error('Total paid must be greater than 0')
      return
    }
    const finalName = name.trim() || generatePurchaseName()
    const qtyPerUnit = Number(quantityPerUnit) >= 0 ? Number(quantityPerUnit) : 1
    onSubmit({
      name: finalName,
      description: description.trim(),
      item: item || undefined,
      quantity: qty,
      quantityPerUnit: qtyPerUnit,
      total: totalAmount,
    })
  }

  const canSubmit = item && Number(quantity) > 0 && Number(total) > 0

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Name (optional, auto-generated if empty)</label>
        <input
          type="text"
          value={name}
          onChange={(e) => {
            setName(e.target.value)
            setNameWasAutogenerated(false)
          }}
          onFocus={() => {
            if (nameWasAutogenerated) {
              setName('')
              setNameWasAutogenerated(false)
            }
          }}
          onBlur={() => {
            if (!name.trim()) {
              setName(generatePurchaseName())
              setNameWasAutogenerated(true)
            }
          }}
          className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-amber-500"
          placeholder="e.g. Supplier order #123"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Description (optional)</label>
        <textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-amber-500"
          rows={2}
          placeholder="Notes"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Item</label>
        <SearchableDropdown
          options={itemOptions}
          valueKey="_id"
          labelKey="label"
          value={item}
          onChange={setItem}
          placeholder="Select item"
        />
      </div>

      <div className="grid gap-4 sm:grid-cols-3">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Quantity (e.g. 6)</label>
          <FormattedNumberInput
            value={quantity}
            onChange={(val) => setQuantity(Math.max(1, Number(val) || 0))}
            min={1}
            className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="1"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Amount per unit (in item&apos;s unit)</label>
          <FormattedNumberInput
            value={quantityPerUnit}
            onChange={setQuantityPerUnit}
            min={0}
            className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="e.g. 1000"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Total paid</label>
          <FormattedNumberInput
            value={total}
            onChange={setTotal}
            min={0}
            className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="0"
          />
          <p className="text-xs text-gray-500 mt-0.5">Including delivery, fees, etc.</p>
        </div>
      </div>

      <div className="flex flex-wrap gap-4 text-sm text-gray-600">
        <p>
          You&apos;re getting: <span className="font-medium text-gray-900">{formatNumber(totalItemAmount)}{preferredSymbol ? ` ${preferredSymbol}` : ''}</span> of this item
        </p>
        <p>
          Total paid: <span className="font-medium text-gray-900">{formatNumber(total)}</span>
        </p>
        {Number(quantity) > 0 && Number(total) > 0 && (
          <p>
            Effective per unit: <span className="font-medium text-gray-900">{formatNumber(effectivePerUnit)}</span>
          </p>
        )}
      </div>

      <div className="flex gap-2 pt-2">
        <button
          type="submit"
          disabled={!canSubmit}
          className="px-4 py-2 rounded bg-amber-500 text-gray-900 hover:bg-amber-400 font-medium focus:outline-none focus:ring-2 focus:ring-amber-400 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isEdit ? 'Update' : 'Save'}
        </button>
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 rounded bg-gray-200 text-gray-800 hover:bg-gray-300 font-medium focus:outline-none focus:ring-2 focus:ring-gray-300"
          >
            Cancel
          </button>
        )}
      </div>
    </form>
  )
}

export default PurchaseForm
