import { useState, useEffect } from 'react'
import toast from 'react-hot-toast'
import SearchableDropdown from '../SearchableDropdown'
import FormattedNumberInput from '../FormattedNumberInput'
import { formatNumber } from '../../helper/formatHelper'

const generateSaleName = () =>
  `Sale ${new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`

const SoldForm = ({
  initialValues,
  products = [],
  onSubmit,
  onCancel,
  isEdit,
}) => {
  const [name, setName] = useState('')
  const [nameWasAutogenerated, setNameWasAutogenerated] = useState(false)
  const [description, setDescription] = useState('')
  const [product, setProduct] = useState('')
  const [quantity, setQuantity] = useState(1)
  const [pricePerQuantity, setPricePerQuantity] = useState(0)
  const [checkBom, setCheckBom] = useState(false)

  const productOptions = products.map((p) => {
    const suffix = p.unitSet?.symbol ?? p.unitSet?.description ?? ''
    const label = suffix ? `${p.name} (${suffix})` : p.name
    return { _id: p._id, label }
  })

  const total = Number(quantity) * Number(pricePerQuantity)

  useEffect(() => {
    if (initialValues) {
      setName(initialValues.name ?? '')
      setNameWasAutogenerated(false)
      setDescription(initialValues.description ?? '')
      setProduct(initialValues.product?._id ?? initialValues.product ?? '')
      setQuantity(Math.max(1, Number(initialValues.quantity) || 1))
      setPricePerQuantity(initialValues.pricePerQuantity ?? 0)
      setCheckBom(!!initialValues.checkBom)
    } else {
      setName(generateSaleName())
      setNameWasAutogenerated(true)
      setDescription('')
      setProduct('')
      setQuantity(1)
      setPricePerQuantity(0)
      setCheckBom(false)
    }
  }, [initialValues, products])

  const handleProductChange = (id) => {
    setProduct(id)
    const prod = products.find((p) => p._id === id)
    if (prod != null && prod.price != null) {
      setPricePerQuantity(Number(prod.price))
    }
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!product || !product.trim()) {
      toast.error('Please select a product')
      return
    }
    const qty = Number(quantity) || 0
    const pricePer = Number(pricePerQuantity) || 0
    if (qty <= 0) {
      toast.error('Quantity must be greater than 0')
      return
    }
    if (pricePer <= 0) {
      toast.error('Price per quantity must be greater than 0')
      return
    }
    const finalName = name.trim() || generateSaleName()
    onSubmit({
      name: finalName,
      description: description.trim(),
      product: product || undefined,
      quantity: qty,
      pricePerQuantity: pricePer,
      total: qty * pricePer,
      checkBom,
    })
  }

  const canSubmit = product && Number(quantity) > 0 && Number(pricePerQuantity) > 0

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Name (optional, auto-generated if empty)</label>
        <input
          type="text"
          value={name}
          onChange={(e) => {
            setName(e.target.value)
            setNameWasAutogenerated(false)
          }}
          onFocus={() => {
            if (nameWasAutogenerated) {
              setName('')
              setNameWasAutogenerated(false)
            }
          }}
          onBlur={() => {
            if (!name.trim()) {
              setName(generateSaleName())
              setNameWasAutogenerated(true)
            }
          }}
          className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-amber-500"
          placeholder="e.g. Sale #123"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Description (optional)</label>
        <textarea
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-amber-500"
          rows={2}
          placeholder="Notes"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Product</label>
        <SearchableDropdown
          options={productOptions}
          valueKey="_id"
          labelKey="label"
          value={product}
          onChange={handleProductChange}
          placeholder="Select product"
        />
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
          <FormattedNumberInput
            value={quantity}
            onChange={(val) => setQuantity(Math.max(1, Number(val) || 0))}
            min={1}
            className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="1"
          />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Price per quantity (defaults to product price)</label>
          <FormattedNumberInput
            value={pricePerQuantity}
            onChange={setPricePerQuantity}
            min={0}
            className="w-full bg-gray-50 border border-gray-300 rounded px-3 py-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-amber-500"
            placeholder="0"
          />
        </div>
      </div>

      <div>
        <p className="text-sm text-gray-600">
          Total: <span className="font-medium text-gray-900">{formatNumber(total)}</span>
        </p>
      </div>

      <div className="flex items-center gap-2">
        <input
          type="checkbox"
          id="checkBom"
          checked={checkBom}
          onChange={(e) => setCheckBom(e.target.checked)}
          className="rounded border-gray-300 text-amber-600 focus:ring-amber-500"
        />
        <label htmlFor="checkBom" className="text-sm text-gray-700">
          Check BOM (deduct materials) – when checked, validates item stock and decreases quantities when sold; unchecked bypasses this
        </label>
      </div>

      <div className="flex gap-2 pt-2">
        <button
          type="submit"
          disabled={!canSubmit}
          className="px-4 py-2 rounded bg-amber-500 text-gray-900 hover:bg-amber-400 font-medium focus:outline-none focus:ring-2 focus:ring-amber-400 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isEdit ? 'Update' : 'Save'}
        </button>
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 rounded bg-gray-200 text-gray-800 hover:bg-gray-300 font-medium focus:outline-none focus:ring-2 focus:ring-gray-300"
          >
            Cancel
          </button>
        )}
      </div>
    </form>
  )
}

export default SoldForm
